version: '2'
services:
  assetservice-app:
    image: assetservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://assetservice-postgresql:5432/assetservice
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  assetservice-postgresql:
    extends:
      file: postgresql.yml
      service: assetservice-postgresql
